### ISSUE TITLE
Where to Find Model and Dataset Files

### ISSUE THREAD

**Issue by VincLee8188** [deepmind/jax_verify#11]
I'm currently using your repository and I'm looking for the model and dataset files that are used in the project. I've reviewed the repository's README and documentation, but I couldn't locate specific instructions on where to find these files.

Could you please provide guidance on where I can find the following:

1. Model Files: I'm interested in the pre-trained model files that the project uses for inference. Are these available in the repository, or should I download them from a specific source?

2. Dataset Files: Additionally, I'd like to access the dataset used for training or evaluation. Could you please specify where I can obtain these dataset files?

It would be immensely helpful if you could provide details or direct links to these files if they exist within the repository or if they are hosted externally.

Thank you for your assistance, and I'm looking forward to exploring and working with your project.

**Comment by bunelr** [comment]
Hi :) 

The models and dataset files are stored on Google Cloud.  The examples use [this function](https://github.com/google-deepmind/jax_verify/blob/master/jax_verify/src/utils.py#L45-L54) to open them, and will download them if they are not present already.

Example of content:
Models: `models/raghunathan18_pgdnn.pkl`, `models/mnist_wongsmall_eps_10_adv.pkl`,  `models/cifar10_wongsmall_eps2_mix.pkl`

Datasets: `mnist/x_test.npy`, `mnist/y_test.npy`, `cifar10/x_test.npy`, 'cifar10/y_test.npy`
